#first we print the list of students
puts "The students of my cohort at Makers Academy"
puts "----------------"
puts "Roi Discoll"
puts "James Whyte"
puts "Margherita Serino"
puts "Vaidas Mykolaitis"
puts "Johann Bornman"
puts "Kate Hamilton"
puts "James Keap"
puts "Nic Yeeles"
puts "Julie Walker"
puts "Will Allen"
puts "Julia Tan"
puts "Federico Maffei"
puts "Jamie Patel"
puts "Faezrah Rizalman"
puts "Josh Fail-Broon"
puts "Sasha Cooper"
puts "Nicolai DTH"
puts "Nadav Matalon"
puts "Fitsum Teklehaimanot"
#finally, we print the total
print "Overall, we have "
#it's important that print() doesn't add new line characters
print 19
puts " great students"
